export const projects = [
  {
    id: 1,
    title: "Loved Ones ",
    description: " The AI app that allows you to create a heartfelt video featuring your Loved Ones who have passed away",
    image: "https://lovedones.ai/include/images/logo.png",
    technologies: ["React Native", "Python", "Sql", "Stripe"],
    category: "react_native",
    demoLink: "https://lovedones.ai/",
    githubLink: "N/A",
    allowGithub: false,
    status: "discontinued",
    pic:true,

  },
  {
    id: 2,
    title: "sybo.ai App",
    description: "A collaborative task management application with real-time updates, team features, and analytics.",
    image: "https://sybo.ai/include/images/logo.png",
   technologies: ["React Native", "Python", "Sql", "Stripe"],
    category: "react_native",
    demoLink: "https://sybo.ai/",
    githubLink: "N/A",
    allowGithub: false,
    status: "active",
    pic:true,
  },
  // {
  //   id: 3,
  //   title: "Weather Dashboard",
  //   description: "Real-time weather dashboard with location-based forecasts, interactive maps, and weather alerts.",
  //   image: "/images/projects/project3.jpg",
  //   technologies: ["React", "OpenWeather API", "Chart.js"],
  //   category: "frontend",
  //   demoLink: "https://demo.com",
  //   githubLink: "https://github.com/tendulkarsuriya/project3",
  // },
  // {
  //   id: 4,
  //   title: "Blog Platform",
  //   description: "A modern blogging platform with markdown support, SEO optimization, and content management.",
  //   image: "/images/projects/project4.jpg",
  //   technologies: ["Next.js", "PostgreSQL", "Prisma"],
  //   category: "fullstack",
  //   demoLink: "https://demo.com",
  //   githubLink: "https://github.com/tendulkarsuriya/project4",
  // },
  // {
  //   id: 5,
  //   title: "REST API Service",
  //   description: "Scalable REST API with authentication, rate limiting, and comprehensive documentation.",
  //   image: "/images/projects/project5.jpg",
  //   technologies: ["Node.js", "Express", "MongoDB", "JWT"],
  //   category: "backend",
  //   demoLink: "https://demo.com",
  //   githubLink: "https://github.com/tendulkarsuriya/project5",
  // },
  {
    id: 6,
    title: "Portfolio Website",
    description: "A modern, responsive portfolio website with smooth animations and dark mode support.",
    image: "/images/projects/project6.jpg",
    technologies: ["Next.js", "Tailwind CSS"],
    category: "frontend",
    demoLink: "https://demo.com",
    githubLink: "https://github.com/tendulkarsuriya/project6",
    allowGithub: true,
    status: "active",
    pic:false,

    
  },
];

export const categories = [
  { id: "all", label: "All Projects" },
  { id: "react_native", label: "React Native" },
  { id: "frontend", label: "Frontend" },
  // { id: "backend", label: "Backend" },
];
